Add Cups choice options
gaithernOrg/ArchipelagoKH1FM pull request #2
Opened 2024-12-27 19:21 UTC by esutley

Makes Cups a choice rather than a toggle, with options that progressively add in the 3 base cups, Hades cup, and then Ice Titan.

Did some test generations and looks to be working as intended. Presets were just based off vibes.

2024-12-27 20:52 UTC, esutley commented
Could also see having Ice Titan be enabled by having Superbosses and Hades Cup both enabled rather than a specific setting for Cups. Don't know about including it in the final door conditions though

2025-01-03 19:21 UTC, gaithern requested changes

2025-01-03 19:21 UTC, gaithern commented on worlds/kh1/Options.py
We should maybe reword that first line to something like:
"Determines which cups have their locations added to the multiworld."

2025-01-04 15:49 UTC, gaithern approved these changes

2025-01-04 15:49 UTC, merged